name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Build and Deploy
          uses: irina-novozhilova/otus-css-novozhilova@master
          env:
            ACCESS_TOKEN: $
            BRANCH: gh-pages
            FOLDER: dist
            BUILD_SCRIPT: npm install && npm run build
